export const products = [
  {
    flavor: "Vanilla",
    ingredients: ["Cream, ", "Sugar, ", "Vanilla extract"],
    price: 4.99,
    image: "https://i.imgur.com/xNq7ZU3.png",
  },
  {
    flavor: "Chocolate",
    ingredients: ["Cream, ", "Sugar, ", "Cocoa powder"],
    price: 5.49,
    image: "https://i.imgur.com/CmjgnIZ.png",
  },
  {
    flavor: "Strawberry",
    ingredients: ["Cream, ", "Sugar, ", "Strawberries"],
    price: 5.29,
    image: "https://i.imgur.com/RgkFfOp.png",
  },
  {
    flavor: "Mint Chocolate Chip",
    ingredients: ["Cream, ", "Sugar, ", "Mint extract, ", "Chocolate chips"],
    price: 5.99,
    image: "https://i.imgur.com/IwpQAHn.png",
  },
  {
    flavor: "Cookie Dough",
    ingredients: ["Cream, ", "Sugar, ", "Cookie dough chunks"],
    price: 6.49,
    image: "https://i.imgur.com/PWuwRBr.png",
  },
  {
    flavor: "Rocky Road",
    ingredients: [
      "Cream, ",
      "Sugar, ",
      "Marshmallows, ",
      "Chocolate, ",
      "Almonds",
    ],
    price: 6.79,
    containsNuts: true,
    image: "https://i.imgur.com/2yzPCUj.png",
  },
  {
    flavor: "Butter Pecan",
    ingredients: ["Cream, ", "Sugar, ", "Butter, ", "Pecans"],
    price: 6.89,
    containsNuts: true,
    image: "https://i.imgur.com/WUmhPDZ.png",
  },
  {
    flavor: "Coffee",
    ingredients: ["Cream, ", "Sugar, ", "Coffee extract"],
    price: 5.79,
    image: "https://i.imgur.com/kjKcYT5.png",
  },
  {
    flavor: "Caramel Swirl",
    ingredients: ["Cream, ", "Sugar, ", "Caramel swirl"],
    price: 6.59,
    image: "https://i.imgur.com/Y0r64rU.png",
  },
  {
    flavor: "Pistachio",
    ingredients: ["Cream, ", "Sugar, ", "Pistachio nuts"],
    price: 6.69,
    containsNuts: true,
    image: "https://i.imgur.com/1wQWLP5.png",
  },
];
